/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      description: string
      subject_type: string
      subject_id: number
      causer: string
      properties: string
      ip_address: string
      user_id: number
    }
    ai_insights: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      kind: string
      selection_id: number
      market_event_id: number
      feature_hash: string
      stance: "back" | "lay" | "pass"
      stated_prob: number
      confidence: number
      summary: string
      rationale: string
      caveats: string
      model: string
      prompt_tokens: number
      completion_tokens: number
      cost_usd: number
      latency_ms: number
      outcome: number
      brier_score: number
      graded_at: string
    }
    alert_subscriptions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number | bigint
      kind: string
      leagues: string
      venue: string
      min_value: number
      channels: string
      active: number
      last_sent_at: string
    }
    analytics_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      category: string
      path: string
      value: number
      currency: string
      properties: string
    }
    api_keys: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number | bigint
      name: string
      prefix: string
      hash: string
      last_used_at: string
      revoked_at: string
    }
    api_usage: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      api_key_id: number
      day: string
      endpoint: string
      requests: number
    }
    athlete_career_records: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      category: string
      external_id: string
      title: string
      season: string
      competition: string
      sports_team_id: number | bigint
      team_name: string
      occurred_on: string
      ended_on: string
      details: string
      athlete_id: number
    }
    athlete_identities: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      external_id: string
      canonical_url: string
      external_name: string
      aliases: string
      profile_facts: string
      last_seen_at: string
      athlete_id: number
    }
    athlete_injuries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      injury_type: string
      started_on: string
      ended_on: string
      days_missed: number
      games_missed: number
      status: string
      provider: string
      athlete_id: number
    }
    athlete_market_values: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      value_eur: number | bigint
      valued_on: string
      team_name: string
      provider: string
      athlete_id: number
    }
    athlete_season_stats: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      sports_team_id: number | bigint
      season: string
      competition: string
      appearances: number
      starts: number
      minutes: number
      points: number
      goals: number
      assists: number
      metrics: string
      provider: string
      athlete_id: number
    }
    athlete_team_memberships: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      started_on: string
      ended_on: string
      squad_number: number
      role: string
      competition: string
      source: string
      athlete_id: number
      sports_team_id: number
    }
    athlete_transfers: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      from_sports_team_id: number | bigint
      to_sports_team_id: number | bigint
      from_team_name: string
      to_team_name: string
      kind: string
      season: string
      transferred_on: string
      fee_eur: number | bigint
      market_value_eur: number | bigint
      provider: string
      external_id: string
      athlete_id: number
    }
    athletes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      search_key: string
      given_name: string
      family_name: string
      date_of_birth: string
      place_of_birth: string
      nationality: string
      second_nationality: string
      position: string
      secondary_positions: string
      height_cm: number
      preferred_foot: string
      shirt_number: number
      joined_on: string
      contract_expires_on: string
      agent_name: string
      outfitter: string
      status: "active" | "inactive" | "retired" | "deceased"
      image_url: string
      last_seen_at: string
      sport_id: number
      sports_team_id: number
    }
    auction_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      lot_number: number
      title: string
      description: string
      image_url: string
      category: string
      donor_name: string
      fair_market_value: number
      starting_bid: number
      min_increment: number
      buy_now_price: number
      reserve_price: number
      status: "open" | "closed" | "sold" | "passed"
      closes_at: string
      extension_count: number
      auction_id: number
    }
    auctions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      event_id: number
      title: string
      description: string
      status: "draft" | "preview" | "open" | "closed" | "settled"
      currency: string
      goal_amount: number
      opens_at: string
      closes_at: string
      anti_snipe_minutes: number
      extend_on_bid_window_minutes: number
      max_extensions: number
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      bio: string
      avatar: string
      user_id: number
    }
    automation_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled"
      current_node_id: string
      version: number
      subject_type: string
      subject_id: string
      context: unknown
      idempotency_key: string
      started_at: string
      finished_at: string
      error: string
      team_id: number
      automation_id: number
    }
    automations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      status: "draft" | "active" | "paused" | "archived"
      version: number
      trigger: unknown
      graph: unknown
      published_at: string
      team_id: number
    }
    backfill_tasks: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      kind: string
      external_id: string
      url: string
      status: "pending" | "running" | "completed" | "failed" | "exhausted"
      priority: number
      attempts: number
      available_at: string
      locked_at: string
      lock_token: string
      completed_at: string
      last_error: string
      document_hash: string
      payload: string
    }
    bet_sheet_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pick: string
      game: string
      league: string
      price: number
      bet_sheet_id: number
    }
    bet_sheets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      token: string
      leg_count: number
      parlay_decimal: number
      user_id: number
    }
    bids: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      bidder_name: string
      bidder_email: string
      amount: number
      max_amount: number
      status: "leading" | "outbid" | "won" | "lost" | "invalid"
      placed_at: string
      auction_id: number
      auction_item_id: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      position: number
      card_limit: number
      color: string
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      icon: string
      color: string
      position: number
      archived: number
      team_id: number
    }
    book_market_coverage: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      market_type: string
      line_count: number
      last_seen_at: string
      bookmaker_id: number
      market_event_id: number
    }
    bookmakers: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      kind: "sportsbook" | "prediction"
      accent: string
      short: string
      provider_key: string
      region: string
      sharp: number
      consensus_weight: number
      active: number
      url: string
      last_seen_at: string
      transport: "" | "json" | "html" | "browser" | "websocket"
      last_success_at: string
      failure_streak: number
    }
    calibration_buckets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      scope: string
      scope_key: string
      bucket_lower: number
      bucket_upper: number
      predicted_avg: number
      observed_rate: number
      sample_size: number
      brier_score: number
      log_loss: number
      avg_clv_pct: number
      computed_at: string
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: "queued" | "deferred" | "sending" | "sent" | "delivered" | "failed" | "undelivered" | "bounced" | "complained" | "suppressed" | "cancelled"
      channel: "email" | "sms" | "push"
      recipient: string
      idempotency_key: string
      provider_message_id: string
      error: string
      sent_at: string
      opened_at: string
      clicked_at: string
      delivered_at: string
      failed_at: string
      segments: number
      cost: number
      metadata: unknown
      team_id: number
      campaign_variant_id: number
    }
    campaign_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      subject: string
      content: unknown
      allocation: number
      sent_count: number
      open_count: number
      click_count: number
      conversion_count: number
      is_winner: number
      team_id: number
      campaign_id: number
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      type: "email" | "sms" | "push" | "social" | "multi-channel"
      status: "draft" | "scheduled" | "sending" | "sent" | "paused" | "cancelled" | "failed" | "active" | "completed" | "archived"
      subject: string
      template: string
      text: string
      content: unknown
      channel_settings: unknown
      segment_definition: unknown
      from_name: string
      from_address: string
      reply_to: string
      timezone: string
      recurrence: string
      experiment_metric: "open_rate" | "click_rate" | "conversion_rate"
      email_list_id: number
      scheduled_at: string
      sent_at: string
      audience_size: number
      sent_count: number
      open_rate: number
      click_rate: number
      conversion_rate: number
      budget: number
      spent: number
      currency: string
      start_date: string
      end_date: string
      team_id: number
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: string
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: number
      board_id: number
      title: string
      description: string
      position: number
      created_by_user_id: number
      due_date: string
      archived: number
      board_column_id: number
      user_id: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: number
      unit_price: number
      total_price: number
      tax_rate: number
      tax_amount: number
      discount_percentage: number
      discount_amount: number
      product_name: string
      product_sku: string
      product_image: string
      notes: string
      cart_id: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "active" | "abandoned" | "converted" | "expired"
      total_items: number
      subtotal: number
      tax_amount: number
      discount_amount: number
      total: number
      expires_at: string
      currency: string
      notes: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      slug: string
      image_url: string
      is_active: number
      parent_category_id: string
      display_order: number
    }
    categorizable_models: {
      // columns
      id: number
      category_id: number
      categorizable_id: number
      categorizable_type: string
      created_at: string
      updated_at: string | null
    }
    closing_lines: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      price: number
      implied_prob: number
      fair_prob: number
      point: number
      captured_at: string
      seconds_before_start: number
      selection_id: number
      bookmaker_id: number
    }
    club_valuations: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      squad_value_eur: number
      squad_size: number
      average_age_years: number
      league_tier: number
      competition: string
      source: string
      external_id: string
      captured_at: string
      sports_team_id: number
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: string
      author_email: string
      content: string
      body: string
      post_title: string
      status: "pending" | "approved" | "spam" | "trash"
      ip_address: string
      user_agent: string
      is_approved: number
      post_id: number
      user_id: number
    }
    communication_suppressions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: string
      channel: "email" | "sms" | "push"
      reason: "unsubscribe" | "bounce" | "complaint" | "carrier" | "manual" | "legal"
      source: string
      suppressed_at: string
      lifted_at: string
      team_id: number
    }
    consent_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: string
      channel: "email" | "sms" | "push"
      action: "requested" | "granted" | "revoked" | "confirmed" | "suppressed"
      purpose: string
      source: string
      jurisdiction: string
      policy_version: string
      idempotency_key: string
      proof: unknown
      ip_address: string
      occurred_at: string
      team_id: number
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      description: string
      status: "Active" | "Scheduled" | "Expired"
      is_active: number
      discount_type: "fixed_amount" | "percentage"
      discount_value: number
      min_order_amount: number
      max_discount_amount: number
      free_product_id: string
      usage_limit: number
      usage_count: number
      start_date: string
      end_date: string
      product_id: number
    }
    courier_pings: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      latitude: number
      longitude: number
      heading: number
      speed: number
      accuracy: number
      recorded_at: string
      courier_id: number
      delivery_route_id: number
    }
    couriers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      phone: string
      vehicle_number: string
      license: string
      status: "active" | "on_delivery" | "on_break" | "offline"
      latitude: number
      longitude: number
      heading: number
      speed: number
      last_ping_at: string
      user_id: number
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      total_spent: number
      last_order: string
      status: "Active" | "Inactive"
      avatar: string
      user_id: number
    }
    dead_letter_jobs: {
      // columns
      id: number
      uuid: string
      connection: string
      queue: string
      payload: string
      exception: string
      reason: string
      total_failures: number
      first_failed_at: string | null
      last_failed_at: string | null
      dead_lettered_at: string
    }
    decision_evidence: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      trade_decision_id: number
      kind: string
      summary: string
      value: number
      contribution: number
      sample_size: number
      window_hours: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      courier: string
      vehicle: string
      stops: number
      delivery_time: number
      total_distance: number
      last_active: number
      status: "planned" | "active" | "completed" | "cancelled"
      started_at: string
      completed_at: string
      courier_id: number
    }
    delivery_stops: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      sequence: number
      status: "pending" | "en_route" | "arrived" | "completed" | "failed" | "skipped"
      address: string
      latitude: number
      longitude: number
      recipient_name: string
      recipient_phone: string
      eta_at: string
      notified_nearby_at: string
      arrived_at: string
      completed_at: string
      notes: string
      type: "pickup" | "dropoff"
      delivery_route_id: number
      order_id: number
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commit_hash: string
      commit_message: string
      branch: string
      status: string
      environment: string
      duration: number
      author: string
      url: string
      error_log: string
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      download_limit: number
      expiry_days: number
      requires_login: number
      automatic_delivery: number
      status: "active" | "inactive"
    }
    drivers: {
      // columns
      id: number
      name: string
      phone: string
      vehicle_number: string
      license: string
      status: string | null
      user_id: number | null
      created_at: string
      updated_at: string | null
      uuid: string | null
    }
    email_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      message_id: string
      recipient: string
      subject: string
      provider: string
      success: number
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      subscribed_at: string
      unsubscribed_at: string
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      subscriber_count: number
      active_count: number
      unsubscribed_count: number
      bounced_count: number
      status: "active" | "inactive" | "archived"
      is_public: number
      double_opt_in: number
    }
    email_suppressions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: string
      type: "bounce" | "complaint" | "unsubscribe" | "manual"
      reason: string
    }
    email_webhook_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: "mailgun" | "postmark" | "ses" | "sendgrid"
      event_id: string
      processed_at: string
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: string
      message: string
      stack: string
      status: number
      additional_info: string
    }
    event_results: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      home_score: number
      away_score: number
      winner_side: string
      period_scores: string
      completed: number
      source: string
      settled_at: string
      graded_at: string
      market_event_id: number
    }
    event_sources: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      external_id: string
      matched_by: "external_id" | "team_pair" | "fuzzy" | "manual"
      confidence: number
      external_title: string
      last_seen_at: string
      rotation_number: number
      market_event_id: number
    }
    exchange_accounts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number | bigint
      venue: string
      label: string
      credentials: string
      masked_identifier: string
      status: string
      balance: number
      last_error: string
      last_synced_at: string
      terms_accepted_at: string
      risk_accepted_at: string
      age_confirmed_at: string
      jurisdiction: string
    }
    exchange_histories: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      exchange_account_id: number
      payload: unknown | null
      synced_at: string | null
      attempted_at: string | null
      last_error: string
    }
    exchange_orders: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      trade_decision_id: number
      exchange_account_id: number
      venue: string
      client_order_id: string
      external_order_id: string
      market_external_id: string
      side: string
      limit_price: number
      size: number
      filled_size: number
      avg_fill_price: number
      status: string
      error: string
      placed_at: string
      accrued_size: number
      accrued_cost: number
    }
    exchange_positions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      trading_strategy_id: number
      exchange_account_id: number
      prediction_market_id: number
      venue: string
      market_external_id: string
      side: string
      size: number
      cost_basis: number
      avg_price: number
      realized_pnl: number
      status: string
      settlement_price: number
      opened_at: string
      settled_at: string
    }
    expert_consensus_snapshots: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      target_key: string
      market_event_id: number
      selection_id: number
      sport: string
      market_type: string
      side: string
      line: number
      has_line: number
      expert_count: number
      pick_count: number
      agreement: number
      weighted_probability: number
      weighted_edge: number
      mean_confidence: number
      total_units: number
      as_of_at: string
      methodology_version: string
      market_id: number
    }
    expert_opinions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      external_id: string
      source_document_id: number
      url: string
      canonical_url: string
      title: string
      content_type: "article" | "pick_card" | "newsletter" | "podcast" | "video" | "social" | "manual"
      sport: string
      league: string
      summary: string
      excerpt: string
      language: string
      paywalled: number
      published_at: string
      ingested_at: string
      parser_version: string
      content_hash: string
      expert_source_id: number
      expert_profile_id: number
    }
    expert_performance_snapshots: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      sport: string
      market_type: string
      window_days: number
      sample_size: number
      wins: number
      losses: number
      pushes: number
      win_rate: number
      units_risked: number
      profit_units: number
      roi: number
      avg_clv_pct: number
      brier_score: number
      calibration_error: number
      as_of_at: string
      methodology_version: string
      expert_profile_id: number
    }
    expert_picks: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      fingerprint: string
      external_id: string
      market_event_id: number
      selection_id: number
      sport: string
      league: string
      event_title: string
      market_type: string
      period: string
      side: string
      line: number
      has_line: number
      odds_american: number
      odds_decimal: number
      sportsbook: string
      units: number
      confidence: number
      rationale: string
      starts_at: string
      published_at: string
      last_seen_at: string
      status: "pending" | "won" | "lost" | "push" | "void" | "ungraded"
      resulted_at: string
      closing_odds_decimal: number
      clv_pct: number
      profit_units: number
      matched_by: "unmatched" | "external_id" | "rotation_number" | "team_pair" | "fuzzy" | "manual"
      match_confidence: number
      expert_source_id: number
      expert_profile_id: number
      expert_opinion_id: number
      market_id: number
    }
    expert_profiles: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      external_id: string
      name: string
      handle: string
      kind: "human" | "model" | "desk" | "show" | "community"
      profile_url: string
      avatar_url: string
      bio: string
      specialties: string
      active: number
      verified: number
      first_seen_at: string
      last_seen_at: string
      expert_source_id: number
    }
    expert_sources: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      key: string
      name: string
      homepage_url: string
      terms_url: string
      robots_url: string
      acquisition: "licensed_feed" | "official_api" | "rss" | "authorized_email" | "public_web" | "manual"
      access_policy: "allowed" | "permission_required" | "blocked_by_terms" | "review_required"
      status: "ready" | "planned" | "active" | "paused" | "blocked"
      parser_key: string
      priority: number
      poll_minutes: number
      attribution_required: number
      retention_days: number
      coverage: string
      notes: string
      last_policy_review_at: string
      last_successful_ingest_at: string
    }
    failed_jobs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      connection: string
      queue: string
      payload: string
      exception: string
      attempts: number
      max_attempts: number
      duration_ms: number
      failed_at: string
    }
    fair_prices: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      prob_consensus: number
      prob_sharp: number
      prob_multiplicative: number
      prob_power: number
      prob_shin: number
      method_spread: number
      fair_price: number
      best_price: number
      best_bookmaker_id: number
      edge_pct: number
      kelly_fraction: number
      overround_pct: number
      book_count: number
      sharp_book_count: number
      computed_at: string
      selection_id: number
    }
    feature_snapshots: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      captured_at: string
      hours_to_start: number
      best_price: number
      fair_prob: number
      sharp_prob: number
      edge_pct: number
      overround_pct: number
      book_count: number
      price_std_dev: number
      open_price: number
      move_from_open_pct: number
      velocity_pct_per_hour: number
      steam_score: number
      reverse_line_move: number
      direction_changes: number
      sport_slug: string
      market_type: string
      side: string
      extra: string
      label: number
      closing_fair_prob: number
      clv_pct: number
      labelled_at: string
      selection_id: number
    }
    form_fields: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      label: string
      type: "text" | "textarea" | "email" | "phone" | "select" | "checkbox" | "radio" | "date" | "file" | "currency" | "section_break"
      required: number
      position: number
      width: "full" | "half"
      options: unknown
      conditions: unknown
      form_id: number
    }
    form_submissions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      data: unknown
      email: string
      name: string
      status: "pending_payment" | "complete" | "spam"
      amount_cents: number
      payment_intent_id: string
      ip: string
      submitted_at: string
      form_id: number
      site_id: number
    }
    forms: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      handle: string
      status: "draft" | "active" | "closed"
      settings: unknown
      site_id: number
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      initial_balance: number
      current_balance: number
      currency: string
      status: "ACTIVE" | "USED" | "EXPIRED" | "DEACTIVATED"
      purchaser_id: string
      recipient_email: string
      recipient_name: string
      personal_message: string
      is_digital: number
      is_reloadable: number
      is_active: number
      expiry_date: string
      last_used_date: string
      template_id: string
      customer_id: number
    }
    group_invitations: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      group_id: number
      invited_by: number
      email: string
      token_hash: string
      expires_at: string
      accepted_at: string | null
      revoked_at: string | null
    }
    group_members: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      group_id: number
      user_id: number
      role: "owner" | "member"
    }
    ingest_runs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      kind: string
      status: "running" | "success" | "partial" | "failed"
      started_at: string
      finished_at: string
      duration_ms: number
      request_count: number
      rows_read: number
      rows_written: number
      unmatched_count: number
      quota_remaining: number
      quota_used: number
      error: string
      summary: string
    }
    job_idempotency: {
      // columns
      id: number
      idempotency_key: string
      job_name: string
      queue: string
      dispatched_at: string
    }
    job_quarantine: {
      // columns
      id: number
      job_name: string
      payload_hash: string
      failure_count: number
      window_start: string
      quarantined_at: string | null
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: string
      payload: string
      attempts: number
      available_at: number
      reserved_at: number
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      color: string
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      template: "Standard License" | "Premium License" | "Enterprise License"
      expiry_date: string
      status: "active" | "inactive" | "unassigned"
      customer_id: number
      product_id: number
      order_id: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: number
      type: "warning" | "error" | "info" | "success"
      source: "file" | "cli" | "system"
      message: string
      project: string
      stacktrace: string
      file: string
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: string
      points: number
      source: string
      source_reference_id: string
      description: string
      expiry_date: string
      is_used: number
      customer_id: number
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      points_required: number
      reward_type: string
      discount_percentage: number
      free_product_id: string
      is_active: number
      expiry_days: number
      image_url: string
      product_id: number
    }
    magic_link_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: string
      token: string
      expires_at: string
      consumed_at: string
      redirect_to: string
      site_id: number
      user_id: number
    }
    mail_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      mailbox: string
      account_name: string
      signature: string
      display_density: "comfortable" | "default" | "compact"
      theme: "light" | "dark" | "system"
      language: "en" | "fr" | "de" | "es" | "ja"
      default_reply_behavior: "reply" | "replyAll"
      send_and_archive: number
      auto_advance: "newer" | "older" | "back"
      desktop_notifications: number
      notification_sound: "default" | "subtle" | "none"
      notification_preview: number
      filters: string
      blocked_senders: string
      labels: string
      load_remote_images: number
      show_external_content: number
      vacation_enabled: number
      vacation_start_date: string
      vacation_end_date: string
      vacation_subject: string
      vacation_message: string
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: string
      description: string
      country: string
      featured: number
    }
    market_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      title: string
      category: string
      league: string
      commence_at: string
      status: "scheduled" | "live" | "final" | "postponed" | "cancelled"
      home_sports_team_id: number
      away_sports_team_id: number
      venue: string
      broadcast: string
      status_detail: string
      last_seen_at: string
      closing_captured_at: string
      sport_id: number
    }
    market_notes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      prediction_market_id: number
      user_id: number | bigint
      author_name: string
      stance: string
      body: string
      hidden: number
    }
    market_traders: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      venue: string
      external_id: string
      alias: string
      trade_count: number
      total_notional: number
      avg_trade_size: number
      max_trade_size: number
      resolved_trade_count: number
      winning_trade_count: number
      win_rate: number
      smart_score: number
      is_whale: number
    }
    market_trades: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      prediction_market_id: number
      market_trader_id: number
      venue: string
      external_id: string
      side: string
      price: number
      size: number
      notional: number
      is_winner: number
      traded_at: string
    }
    markets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      market_type: string
      label: string
      line: number
      line_key: string
      period: string
      player_name: string
      complete: number
      status: "open" | "suspended" | "settled"
      position: number
      market_event_id: number
    }
    menu_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      label: string
      url: string
      target: "_self" | "_blank"
      parent_id: number
      position: number
      visibility: "public" | "auth"
      menu_id: number
      page_id: number
    }
    menus: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      handle: string
      name: string
      site_id: number
    }
    notification_deliveries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number | bigint
      channel: "email" | "sms" | "chat" | "database" | "push" | "broadcast"
      recipient: string
      subject: string
      body: string
      status: "pending" | "sent" | "delivered" | "failed"
      error: string
      metadata: string
      sent_at: string
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      data: string
      read_at: string
      user_id: number
    }
    oauth_access_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      tokenable_type: string
      tokenable_id: number
      name: string
      token: string
      scopes: string
      revoked: number
      expires_at: string
      user_agent: string
      ip_address: string
    }
    odds: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      price: number
      american: number
      implied_prob: number
      point: number
      limit_amount: number
      available: number
      observed_at: string
      link: string
      sid: string
      traded_volume: number
      selection_id: number
      bookmaker_id: number
    }
    odds_snapshots: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      price: number
      implied_prob: number
      point: number
      captured_at: string
      is_opening: number
      selection_id: number
      bookmaker_id: number
    }
    order_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      order_id: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: number
      price: number
      special_instructions: string
      order_id: number
      product_id: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: string
      total_amount: number
      currency: string
      tax_amount: number
      discount_amount: number
      delivery_fee: number
      tip_amount: number
      order_type: string
      delivery_address: string
      special_instructions: string
      estimated_delivery_time: string
      tracking_token: string
      delivery_latitude: number
      delivery_longitude: number
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    page_revisions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      revision: number
      title: string
      blocks: unknown
      meta_description: string
      note: string
      page_id: number
      author_id: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      path: string
      parent_id: number
      template: string
      blocks: unknown
      meta_description: string
      status: "draft" | "published" | "scheduled" | "archived"
      scheduled_at: string
      views: number
      published_at: string
      conversions: number
      author_id: number
      site_id: number
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      last_four: number
      brand: string
      exp_month: number
      exp_year: number
      is_default: number
      provider_id: string
      user_id: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      key: string
      unit_price: number
      status: string
      image: string
      provider_id: string
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      amount: number
      type: string
      provider_id: string
      user_id: number
      payment_method_id: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      method: "cash" | "creditCard" | "debitCard" | "paypal" | "applePay" | "googlePay" | "bankTransfer" | "giftCard"
      status: "pending" | "processing" | "completed" | "failed" | "refunded" | "partiallyRefunded" | "succeeded"
      currency: string
      reference_number: string
      card_last_four: string
      card_brand: string
      billing_email: string
      transaction_id: string
      payment_provider: string
      refund_amount: number
      notes: string
      order_id: number
      customer_id: number
    }
    pledges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      donor_name: string
      donor_email: string
      amount: number
      level: string
      status: "pending" | "confirmed" | "cancelled"
      auction_id: number
      customer_id: number
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      poster: string
      content: string
      excerpt: string
      focus_keyword: string
      meta_description: string
      canonical_url: string
      views: number
      published_at: string
      status: "published" | "draft" | "archived"
      is_featured: number
      author_id: number
      site_id: number
    }
    prediction_groups: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      owner_id: number
      name: string
      description: string
    }
    prediction_markets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      venue: string
      external_id: string
      question: string
      outcome_label: string
      category: string
      status: string
      result: string
      volume: number
      liquidity: number
      last_price: number
      ends_at: string
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      mac_address: string
      location: string
      terminal: string
      status: "online" | "offline" | "warning"
      last_ping: number
      print_count: number
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      abbreviation: string
      type: string
      description: string
      is_default: number
      product_id: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: string
      type: string
      description: string
      options: string
      status: "active" | "inactive" | "draft"
      product_id: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      price: number
      image_url: string
      is_available: number
      inventory_count: number
      preparation_time: number
      allergens: string
      nutritional_info: string
      category_id: number
      manufacturer_id: number
    }
    query_logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      query: string
      normalized_query: string
      duration: number
      connection: string
      status: "completed" | "failed" | "slow"
      error: string
      executed_at: string
      bindings: string
      trace: string
      model: string
      method: string
      file: string
      line: number
      memory_usage: number
      rows_affected: number
      transaction_id: string
      tags: string
      affected_tables: string
      indexes_used: string
      missing_indexes: string
      explain_plan: string
      optimization_suggestions: string
    }
    queue_circuit_state: {
      // columns
      queue_name: string
      success_count: number
      failure_count: number
      window_start: string
      paused_at: string | null
      resume_at: string | null
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: string
      document: string
      timestamp: string
      status: "success" | "failed" | "warning"
      size: number
      pages: number
      duration: number
      metadata: string
      print_device_id: number
    }
    redirects: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      from_path: string
      to_path: string
      status_code: number
      source: "slug-change" | "manual"
      site_id: number
    }
    referral_codes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      code: string
    }
    referrals: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      referrer_id: number
      referred_user_id: number
      code: string
      status: "registered" | "qualified"
      qualified_at: string | null
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: string
      type: string
      status: string
      notes: string
      downloads: number
      author: string
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD"
      path: string
      status_code: number
      duration_ms: number
      ip_address: string
      memory_usage: number
      user_agent: string
      error_message: string
    }
    reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rating: number
      title: string
      content: string
      is_verified_purchase: number
      is_approved: number
      is_featured: number
      helpful_votes: number
      unhelpful_votes: number
      purchase_date: string
      images: string
      product_id: number
      customer_id: number
    }
    selections: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      label: string
      side: string
      point: number
      point_key: string
      position: number
      sports_team_id: number
      outcome: number
      graded_at: string
      market_id: number
    }
    sender_domains: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      domain: string
      status: "pending" | "verified" | "failed" | "disabled"
      selector: string
      dns_records: unknown
      verified_at: string
      last_checked_at: string
      team_id: number
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      base_rate: number
      free_shipping: number
      status: "active" | "inactive" | "draft"
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: number
      weight_to: number
      rate: number
      shipping_method_id: number
      shipping_zone_id: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      countries: string
      regions: string
      postal_codes: string
      status: "active" | "inactive" | "draft"
      shipping_method_id: number
    }
    site_domains: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      domain: string
      is_primary: number
      verified_at: string
      ssl_status: "pending" | "issued" | "failed"
      site_id: number
    }
    sites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      subdomain: string
      status: "active" | "suspended" | "archived"
      settings: unknown
      timezone: string
      team_id: number
    }
    sms_opt_outs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      phone: string
      reason: string
      opted_out_at: string
    }
    social_accounts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      provider_user_id: string
      provider_email: string
      user_id: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: string
      platform: "twitter" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube"
      status: "draft" | "scheduled" | "published" | "failed"
      scheduled_at: string
      published_at: string
      likes: number
      shares: number
      comments: number
      reach: number
      image_url: string
      external_id: string
      user_id: number
    }
    source_documents: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      kind: string
      external_id: string
      url: string
      url_hash: string
      content_hash: string
      storage_path: string
      http_status: number
      content_type: string
      etag: string
      last_modified: string
      byte_length: number | bigint
      fetched_at: string
      parsed_at: string
      parser_version: string
    }
    sports: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      slug: string
      title: string
      grouping: string
      espn_path: string
      odds_api_key: string
      active: number
      position: number
      non_sporting: number
      tier: number
    }
    sports_teams: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      search_key: string
      short_name: string
      abbreviation: string
      aliases: string
      logo: string
      espn_id: string
      record: string
      sport_id: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      source: string
      subscriber_id: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      unsubscribed_at: string
      user_id: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      plan: string
      provider_id: string
      provider_status: string
      unit_price: number
      provider_type: string
      provider_price_id: string
      quantity: number
      trial_ends_at: string
      ends_at: string
      last_used_at: string
      user_id: number
    }
    taggable_models: {
      // columns
      id: number
      tag_id: number
      taggable_id: number
      taggable_type: string
      created_at: string
      updated_at: string | null
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      color: string
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      rate: number
      type: string
      country: string
      region: "North America" | "South America" | "Europe" | "Asia" | "Africa" | "Oceania" | "Antarctica"
      status: "active" | "inactive"
      is_default: number
      code: string
      exemptible: number
    }
    team_identities: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      external_id: string
      canonical_url: string
      external_name: string
      last_seen_at: string
      sports_team_id: number
    }
    team_injuries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      athlete_name: string
      status: string
      injury_type: string
      severity: number
      source: string
      captured_at: string
      sports_team_id: number
    }
    team_invitations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      email: string
      role: "admin" | "member" | "viewer"
      token_hash: string
      pending_key: string
      invited_by_user_id: number
      accepted_by_user_id: number
      status: "pending" | "accepted" | "revoked" | "expired"
      delivery_status: "pending" | "sent" | "failed"
      delivery_error: string
      expires_at: string
      delivered_at: string
      accepted_at: string
    }
    team_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      user_id: number
      role: "owner" | "admin" | "member" | "viewer"
      status: "active" | "suspended"
    }
    team_standings: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      wins: number
      losses: number
      ties: number
      games_played: number
      win_percent: number
      points_for: number
      points_against: number
      point_differential: number
      playoff_seed: number
      group_name: string
      source: string
      captured_at: string
      sports_team_id: number
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      member_count: number
      status: string
    }
    trade_decisions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      trading_strategy_id: number
      prediction_market_id: number
      venue: string
      side: string
      market_price: number
      fair_value: number
      edge: number
      confidence: number
      limit_price: number
      size: number
      notional: number
      rationale: string
      decided_by: string
      status: string
      status_reason: string
    }
    trading_halts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      active: number
      reason: string
      actor: string
    }
    trading_strategies: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number | bigint
      name: string
      venue: string
      categories: string
      bankroll: number
      max_stake: number
      min_edge: number
      min_confidence: number
      max_open_positions: number
      daily_loss_limit: number
      cumulative_loss_limit: number
      mode: string
      auto_execute: number
      status: string
      halted_reason: string
      last_run_at: string
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      status: string
      payment_method: string
      payment_details: string
      transaction_reference: string
      loyalty_points_earned: number
      loyalty_points_redeemed: number
      order_id: number
    }
    usage_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      meter: "contacts" | "email_sends" | "sms_segments" | "ai_generations" | "storage_bytes"
      quantity: number
      idempotency_key: string
      metadata: unknown
      occurred_at: string
      team_id: number
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_verified_at: string | null
      password_changed_at: string | null
      two_factor_secret: string | null
      two_factor_enabled: number | null
      two_factor_last_used_step: number | null
      stripe_id: string | null
      name: string
      email: string
      password: string
      avatar: string
    }
    venue_orders: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      exchange_account_id: number
      prediction_market_id: number | null
      venue: string
      external_order_id: string
      market_external_id: string
      side: string
      limit_price: number
      size: number
      remaining_size: number
      placed_at: string
      synced_at: string
    }
    venue_positions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      exchange_account_id: number
      prediction_market_id: number | null
      venue: string
      market_external_id: string
      side: string
      size: number
      avg_price: number
      synced_at: string
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      quantity: number
      notification_preference: "sms" | "email" | "both"
      source: string
      notes: string
      status: "waiting" | "purchased" | "notified" | "cancelled"
      notified_at: string
      purchased_at: string
      cancelled_at: string
      product_id: number
      customer_id: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      party_size: number
      check_in_time: string
      table_preference: "indoor" | "bar" | "booth" | "no_preference"
      status: "waiting" | "seated" | "cancelled" | "no_show"
      quoted_wait_time: number
      actual_wait_time: number
      queue_position: number
      seated_at: string
      no_show_at: string
      cancelled_at: string
      customer_id: number
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: "disconnection" | "error" | "success"
      socket: string
      details: string
      time: number
    }
  }
}

export {}
