// Auto-generated by stx — do not edit
// Source: resources/views/

export const routes = [
  { pattern: '/features/api', filePath: 'resources/views/features/api.stx', isDynamic: false, params: [] },
  { pattern: '/features/automation', filePath: 'resources/views/features/automation.stx', isDynamic: false, params: [] },
  { pattern: '/features/evidence', filePath: 'resources/views/features/evidence.stx', isDynamic: false, params: [] },
  { pattern: '/features/live', filePath: 'resources/views/features/live.stx', isDynamic: false, params: [] },
  { pattern: '/features/odds', filePath: 'resources/views/features/odds.stx', isDynamic: false, params: [] },
  { pattern: '/features/risk', filePath: 'resources/views/features/risk.stx', isDynamic: false, params: [] },
  { pattern: '/features/sheets', filePath: 'resources/views/features/sheets.stx', isDynamic: false, params: [] },
  { pattern: '/features/smart-money', filePath: 'resources/views/features/smart-money.stx', isDynamic: false, params: [] },
  { pattern: '/', filePath: 'resources/views/index.stx', isDynamic: false, params: [] },
  { pattern: '/account', filePath: 'resources/views/account.stx', isDynamic: false, params: [] },
  { pattern: '/community', filePath: 'resources/views/community.stx', isDynamic: false, params: [] },
  { pattern: '/compare', filePath: 'resources/views/compare.stx', isDynamic: false, params: [] },
  { pattern: '/features', filePath: 'resources/views/features.stx', isDynamic: false, params: [] },
  { pattern: '/live', filePath: 'resources/views/live.stx', isDynamic: false, params: [] },
  { pattern: '/login', filePath: 'resources/views/login.stx', isDynamic: false, params: [] },
  { pattern: '/markets', filePath: 'resources/views/markets.stx', isDynamic: false, params: [] },
  { pattern: '/pipeline', filePath: 'resources/views/pipeline.stx', isDynamic: false, params: [] },
  { pattern: '/pricing', filePath: 'resources/views/pricing.stx', isDynamic: false, params: [] },
  { pattern: '/privacy', filePath: 'resources/views/privacy.stx', isDynamic: false, params: [] },
  { pattern: '/risk', filePath: 'resources/views/risk.stx', isDynamic: false, params: [] },
  { pattern: '/signup', filePath: 'resources/views/signup.stx', isDynamic: false, params: [] },
  { pattern: '/terms', filePath: 'resources/views/terms.stx', isDynamic: false, params: [] },
  { pattern: '/scores/:league/game/:id', filePath: 'resources/views/scores/[league]/game/[id].stx', isDynamic: true, params: ["league","id"] },
  { pattern: '/scores/:league/:day', filePath: 'resources/views/scores/[league]/[day].stx', isDynamic: true, params: ["league","day"] },
  { pattern: '/compare/:competitor', filePath: 'resources/views/compare/[competitor].stx', isDynamic: true, params: ["competitor"] },
] as const

export type RouteName = typeof routes[number]['pattern']
