// Auto-generated by STX - do not edit
declare module '@stacksjs/stx' {
  interface KnownRoutes {
    '/cms/blocks/columns': {  }
    '/cms/blocks/cta': {  }
    '/cms/blocks/embed': {  }
    '/cms/blocks/form': {  }
    '/cms/blocks/hero': {  }
    '/cms/blocks/image': {  }
    '/cms/blocks/rich-text': {  }
    '/checkout/contact': {  }
    '/checkout/payment': {  }
    '/checkout/shipping': {  }
    '/cms/page': {  }
    '/errors/404': {  }
    '/errors/tester': {  }
    '/features/api': {  }
    '/features/automation': {  }
    '/features/evidence': {  }
    '/features/live': {  }
    '/features/odds': {  }
    '/features/risk': {  }
    '/features/sheets': {  }
    '/features/smart-money': {  }
    '/': {  }
    '/account': {  }
    '/cart': {  }
    '/coming-soon': {  }
    '/community': {  }
    '/compare': {  }
    '/dashboard': {  }
    '/features': {  }
    '/forgot-password': {  }
    '/groups': {  }
    '/history': {  }
    '/live': {  }
    '/login': {  }
    '/market': {  }
    '/markets': {  }
    '/odds': {  }
    '/pipeline': {  }
    '/positions': {  }
    '/pricing': {  }
    '/privacy': {  }
    '/register': {  }
    '/risk': {  }
    '/signup': {  }
    '/terms': {  }
    '/scores/:league/game/:id': { league: string; id: string }
    '/auth/magic/:token': { token: string }
    '/password/reset/:token': { token: string }
    '/scores/:league/:day': { league: string; day: string }
    '/compare/:competitor': { competitor: string }
    '/orders/:id': { id: string }
  }
}

export {}
