// Auto-generated by STX - do not edit
declare module "stx/routes" {
  interface RouteMap {
    '/components/FeatureCard': {  }
    '/features/api': {  }
    '/features/automation': {  }
    '/features/evidence': {  }
    '/features/live': {  }
    '/features/odds': {  }
    '/features/risk': {  }
    '/features/sheets': {  }
    '/features/smart-money': {  }
    '/layouts/default': {  }
    '/layouts/marketing': {  }
    '/partials/theme': {  }
    '/': {  }
    '/account': {  }
    '/community': {  }
    '/compare': {  }
    '/features': {  }
    '/live': {  }
    '/login': {  }
    '/markets': {  }
    '/pipeline': {  }
    '/pricing': {  }
    '/privacy': {  }
    '/risk': {  }
    '/signup': {  }
    '/terms': {  }
    '/scores/:league/game/:id': { league: string; id: string }
    '/scores/:league/:day': { league: string; day: string }
    '/compare/:competitor': { competitor: string }
  }
}
