-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "venue_positions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "exchange_account_id" INTEGER REFERENCES "exchange_accounts"("id"),
  "prediction_market_id" INTEGER REFERENCES "prediction_markets"("id"),
  "venue" TEXT,
  "market_external_id" TEXT,
  "side" TEXT,
  "size" REAL,
  "avg_price" REAL,
  "synced_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "venue_positions_account_market_side" ON "venue_positions" ("exchange_account_id", "market_external_id", "side");
CREATE INDEX IF NOT EXISTS "venue_positions_market" ON "venue_positions" ("prediction_market_id");
