-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "expert_consensus_snapshots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "target_key" TEXT not null,
  "market_event_id" INTEGER REFERENCES "market_events"("id") ON DELETE SET NULL,
  "selection_id" INTEGER REFERENCES "selections"("id") ON DELETE SET NULL,
  "sport" TEXT default '',
  "market_type" TEXT default '',
  "side" TEXT default '',
  "line" REAL default 0,
  "has_line" INTEGER default 0,
  "expert_count" INTEGER default 0,
  "pick_count" INTEGER default 0,
  "agreement" REAL default 0,
  "weighted_probability" REAL default 0,
  "weighted_edge" REAL default 0,
  "mean_confidence" REAL default 0,
  "total_units" REAL default 0,
  "as_of_at" TEXT not null,
  "methodology_version" TEXT not null default 'v1',
  "market_id" INTEGER REFERENCES "markets"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "expert_consensus_snapshots_expert_consensus_target_time" ON "expert_consensus_snapshots" ("target_key", "as_of_at");
CREATE INDEX IF NOT EXISTS "expert_consensus_snapshots_expert_consensus_event" ON "expert_consensus_snapshots" ("market_event_id");
CREATE INDEX IF NOT EXISTS "expert_consensus_snapshots_expert_consensus_selection" ON "expert_consensus_snapshots" ("selection_id");
