-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "expert_opinions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "external_id" TEXT not null,
  "source_document_id" INTEGER REFERENCES "source_documents"("id") ON DELETE SET NULL,
  "url" TEXT not null,
  "canonical_url" TEXT default '',
  "title" TEXT not null,
  "content_type" TEXT not null default 'article',
  "sport" TEXT default '',
  "league" TEXT default '',
  "summary" TEXT default '',
  "excerpt" TEXT default '',
  "language" TEXT default 'en',
  "paywalled" INTEGER default 0,
  "published_at" TEXT not null,
  "ingested_at" TEXT not null,
  "parser_version" TEXT default '',
  "content_hash" TEXT default '',
  "expert_source_id" INTEGER REFERENCES "expert_sources"("id"),
  "expert_profile_id" INTEGER REFERENCES "expert_profiles"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "expert_opinions_source_external" ON "expert_opinions" ("expert_source_id", "external_id");
CREATE INDEX IF NOT EXISTS "expert_opinions_expert_published" ON "expert_opinions" ("expert_profile_id", "published_at");
CREATE INDEX IF NOT EXISTS "expert_opinions_document" ON "expert_opinions" ("source_document_id");
CREATE INDEX IF NOT EXISTS "expert_opinions_sport_published" ON "expert_opinions" ("sport", "published_at");
