-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "expert_picks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "fingerprint" TEXT not null,
  "external_id" TEXT default '',
  "market_event_id" INTEGER REFERENCES "market_events"("id") ON DELETE SET NULL,
  "selection_id" INTEGER REFERENCES "selections"("id") ON DELETE SET NULL,
  "sport" TEXT default '',
  "league" TEXT default '',
  "event_title" TEXT default '',
  "market_type" TEXT not null,
  "period" TEXT default 'full_game',
  "side" TEXT not null,
  "line" REAL default 0,
  "has_line" INTEGER default 0,
  "odds_american" INTEGER default 0,
  "odds_decimal" REAL default 0,
  "sportsbook" TEXT default '',
  "units" REAL default 0,
  "confidence" REAL default 0,
  "rationale" TEXT default '',
  "starts_at" TEXT default '',
  "published_at" TEXT not null,
  "last_seen_at" TEXT default '',
  "status" TEXT not null default 'pending',
  "resulted_at" TEXT default '',
  "closing_odds_decimal" REAL default 0,
  "clv_pct" REAL default 0,
  "profit_units" REAL default 0,
  "matched_by" TEXT default 'unmatched',
  "match_confidence" REAL default 0,
  "expert_source_id" INTEGER REFERENCES "expert_sources"("id"),
  "expert_profile_id" INTEGER REFERENCES "expert_profiles"("id"),
  "expert_opinion_id" INTEGER REFERENCES "expert_opinions"("id"),
  "market_id" INTEGER REFERENCES "markets"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "expert_picks_source_fingerprint" ON "expert_picks" ("expert_source_id", "fingerprint");
CREATE INDEX IF NOT EXISTS "expert_picks_expert_published" ON "expert_picks" ("expert_profile_id", "published_at");
CREATE INDEX IF NOT EXISTS "expert_picks_event" ON "expert_picks" ("market_event_id");
CREATE INDEX IF NOT EXISTS "expert_picks_selection" ON "expert_picks" ("selection_id");
CREATE INDEX IF NOT EXISTS "expert_picks_status_starts" ON "expert_picks" ("status", "starts_at");
