-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "expert_performance_snapshots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "sport" TEXT default 'all',
  "market_type" TEXT default 'all',
  "window_days" INTEGER not null default 365,
  "sample_size" INTEGER default 0,
  "wins" INTEGER default 0,
  "losses" INTEGER default 0,
  "pushes" INTEGER default 0,
  "win_rate" REAL default 0,
  "units_risked" REAL default 0,
  "profit_units" REAL default 0,
  "roi" REAL default 0,
  "avg_clv_pct" REAL default 0,
  "brier_score" REAL default 0,
  "calibration_error" REAL default 0,
  "as_of_at" TEXT not null,
  "methodology_version" TEXT not null default 'v1',
  "expert_profile_id" INTEGER REFERENCES "expert_profiles"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "expert_performance_snapshots_expert_perf_scope" ON "expert_performance_snapshots" ("expert_profile_id", "sport", "market_type", "window_days", "as_of_at");
CREATE INDEX IF NOT EXISTS "expert_performance_snapshots_expert_perf_as_of" ON "expert_performance_snapshots" ("as_of_at");
