-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "expert_sources" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "key" TEXT not null,
  "name" TEXT not null,
  "homepage_url" TEXT default '',
  "terms_url" TEXT default '',
  "robots_url" TEXT default '',
  "acquisition" TEXT not null default 'licensed_feed',
  "access_policy" TEXT not null default 'review_required',
  "status" TEXT not null default 'planned',
  "parser_key" TEXT default '',
  "priority" INTEGER default 3,
  "poll_minutes" INTEGER default 60,
  "attribution_required" INTEGER default 1,
  "retention_days" INTEGER default 365,
  "coverage" TEXT default '',
  "notes" TEXT default '',
  "last_policy_review_at" TEXT default '',
  "last_successful_ingest_at" TEXT default '',
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "expert_sources_key" ON "expert_sources" ("key");
CREATE INDEX IF NOT EXISTS "expert_sources_status_policy" ON "expert_sources" ("status", "access_policy");
