-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "venue_orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "exchange_account_id" INTEGER REFERENCES "exchange_accounts"("id"),
  "prediction_market_id" INTEGER REFERENCES "prediction_markets"("id"),
  "venue" TEXT,
  "external_order_id" TEXT,
  "market_external_id" TEXT,
  "side" TEXT,
  "limit_price" REAL,
  "size" REAL,
  "remaining_size" REAL,
  "placed_at" TEXT,
  "synced_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "venue_orders_account_external_id" ON "venue_orders" ("exchange_account_id", "external_order_id");
CREATE INDEX IF NOT EXISTS "venue_orders_market" ON "venue_orders" ("prediction_market_id");
