-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "expert_profiles" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "external_id" TEXT not null,
  "name" TEXT not null,
  "handle" TEXT default '',
  "kind" TEXT not null default 'human',
  "profile_url" TEXT default '',
  "avatar_url" TEXT default '',
  "bio" TEXT default '',
  "specialties" TEXT default '',
  "active" INTEGER default 1,
  "verified" INTEGER default 0,
  "first_seen_at" TEXT default '',
  "last_seen_at" TEXT default '',
  "expert_source_id" INTEGER REFERENCES "expert_sources"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "expert_profiles_source_external" ON "expert_profiles" ("expert_source_id", "external_id");
CREATE INDEX IF NOT EXISTS "expert_profiles_name" ON "expert_profiles" ("name");
CREATE INDEX IF NOT EXISTS "expert_profiles_active" ON "expert_profiles" ("active");
