-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "group_invitations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "group_id" INTEGER not null,
  "invited_by" INTEGER not null,
  "email" TEXT default '',
  "token_hash" TEXT not null,
  "expires_at" TEXT not null,
  "accepted_at" TEXT,
  "revoked_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "group_invitations_group" ON "group_invitations" ("group_id");
CREATE UNIQUE INDEX IF NOT EXISTS "group_invitations_token_hash_unique" ON "group_invitations" ("token_hash");
