-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "exchange_histories" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "exchange_account_id" INTEGER not null,
  "payload" TEXT,
  "synced_at" TEXT,
  "attempted_at" TEXT,
  "last_error" TEXT default '',
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "exchange_histories_exchange_account_id_unique" ON "exchange_histories" ("exchange_account_id");
