-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "group_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "group_id" INTEGER not null,
  "user_id" INTEGER not null,
  "role" TEXT CHECK ("role" IN ('owner', 'member')) not null default 'member',
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "group_members_group_user_unique" ON "group_members" ("group_id", "user_id");
