-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `group_members` (
  `id` bigint PRIMARY KEY auto_increment,
  `group_id` integer not null,
  `user_id` integer not null,
  `role` ENUM('owner', 'member') not null default 'member',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `group_members_group_user_unique` ON `group_members` (`group_id`, `user_id`);
