-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `expert_profiles` (
  `id` bigint PRIMARY KEY auto_increment,
  `external_id` varchar(200) not null,
  `name` varchar(200) not null,
  `handle` varchar(160) default '',
  `kind` varchar(255) not null default 'human',
  `profile_url` text default (''),
  `avatar_url` text default (''),
  `bio` text default (''),
  `specialties` text default (''),
  `active` tinyint(1) default 1,
  `verified` tinyint(1) default 0,
  `first_seen_at` varchar(40) default '',
  `last_seen_at` varchar(40) default '',
  `expert_source_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `expert_profiles_expert_source_id_fk` FOREIGN KEY (`expert_source_id`) REFERENCES `expert_sources`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `expert_profiles_source_external` ON `expert_profiles` (`expert_source_id`, `external_id`);
CREATE INDEX `expert_profiles_name` ON `expert_profiles` (`name`);
CREATE INDEX `expert_profiles_active` ON `expert_profiles` (`active`);
