-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `expert_performance_snapshots` (
  `id` bigint PRIMARY KEY auto_increment,
  `sport` varchar(60) default 'all',
  `market_type` varchar(80) default 'all',
  `window_days` integer not null default 365,
  `sample_size` integer default 0,
  `wins` integer default 0,
  `losses` integer default 0,
  `pushes` integer default 0,
  `win_rate` decimal(10,2) default 0,
  `units_risked` decimal(10,2) default 0,
  `profit_units` decimal(10,2) default 0,
  `roi` decimal(10,2) default 0,
  `avg_clv_pct` decimal(10,2) default 0,
  `brier_score` decimal(10,2) default 0,
  `calibration_error` decimal(10,2) default 0,
  `as_of_at` varchar(40) not null,
  `methodology_version` varchar(40) not null default 'v1',
  `expert_profile_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `expert_performance_snapshots_expert_profile_id_fk` FOREIGN KEY (`expert_profile_id`) REFERENCES `expert_profiles`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `expert_performance_snapshots_expert_perf_scope` ON `expert_performance_snapshots` (`expert_profile_id`, `sport`, `market_type`, `window_days`, `as_of_at`);
CREATE INDEX `expert_performance_snapshots_expert_perf_as_of` ON `expert_performance_snapshots` (`as_of_at`);
