-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `group_invitations` (
  `id` bigint PRIMARY KEY auto_increment,
  `group_id` integer not null,
  `invited_by` integer not null,
  `email` varchar(254) default '',
  `token_hash` varchar(64) not null,
  `expires_at` date not null,
  `accepted_at` date,
  `revoked_at` date,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `group_invitations_group` ON `group_invitations` (`group_id`);
CREATE UNIQUE INDEX `group_invitations_token_hash_unique` ON `group_invitations` (`token_hash`);
