-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `venue_positions` (
  `id` bigint PRIMARY KEY auto_increment,
  `exchange_account_id` bigint,
  `prediction_market_id` bigint,
  `venue` varchar(20),
  `market_external_id` varchar(120),
  `side` varchar(60),
  `size` decimal(10,2),
  `avg_price` decimal(10,2),
  `synced_at` varchar(40),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `venue_positions_exchange_account_id_fk` FOREIGN KEY (`exchange_account_id`) REFERENCES `exchange_accounts`(`id`),
  CONSTRAINT `venue_positions_prediction_market_id_fk` FOREIGN KEY (`prediction_market_id`) REFERENCES `prediction_markets`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `venue_positions_account_market_side` ON `venue_positions` (`exchange_account_id`, `market_external_id`, `side`);
CREATE INDEX `venue_positions_market` ON `venue_positions` (`prediction_market_id`);
