-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `expert_consensus_snapshots` (
  `id` bigint PRIMARY KEY auto_increment,
  `target_key` varchar(240) not null,
  `market_event_id` bigint,
  `selection_id` bigint,
  `sport` varchar(60) default '',
  `market_type` varchar(80) default '',
  `side` varchar(240) default '',
  `line` decimal(10,2) default 0,
  `has_line` tinyint(1) default 0,
  `expert_count` integer default 0,
  `pick_count` integer default 0,
  `agreement` decimal(10,2) default 0,
  `weighted_probability` decimal(10,2) default 0,
  `weighted_edge` decimal(10,2) default 0,
  `mean_confidence` decimal(10,2) default 0,
  `total_units` decimal(10,2) default 0,
  `as_of_at` varchar(40) not null,
  `methodology_version` varchar(40) not null default 'v1',
  `market_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `expert_consensus_snapshots_market_event_id_fk` FOREIGN KEY (`market_event_id`) REFERENCES `market_events`(`id`) ON DELETE SET NULL,
  CONSTRAINT `expert_consensus_snapshots_selection_id_fk` FOREIGN KEY (`selection_id`) REFERENCES `selections`(`id`) ON DELETE SET NULL,
  CONSTRAINT `expert_consensus_snapshots_market_id_fk` FOREIGN KEY (`market_id`) REFERENCES `markets`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `expert_consensus_snapshots_expert_consensus_target_time` ON `expert_consensus_snapshots` (`target_key`, `as_of_at`);
CREATE INDEX `expert_consensus_snapshots_expert_consensus_event` ON `expert_consensus_snapshots` (`market_event_id`);
CREATE INDEX `expert_consensus_snapshots_expert_consensus_selection` ON `expert_consensus_snapshots` (`selection_id`);
