-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `referrals` (
  `id` bigint PRIMARY KEY auto_increment,
  `referrer_id` integer not null,
  `referred_user_id` integer not null,
  `code` varchar(24) not null,
  `status` ENUM('registered', 'qualified') not null default 'registered',
  `qualified_at` date,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `referrals_referrer_status` ON `referrals` (`referrer_id`, `status`);
CREATE UNIQUE INDEX `referrals_referred_user_id_unique` ON `referrals` (`referred_user_id`);
