-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `exchange_histories` (
  `id` bigint PRIMARY KEY auto_increment,
  `exchange_account_id` integer not null,
  `payload` json,
  `synced_at` datetime,
  `attempted_at` datetime,
  `last_error` varchar(500) default '',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `exchange_histories_exchange_account_id_unique` ON `exchange_histories` (`exchange_account_id`);
