-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `expert_sources` (
  `id` bigint PRIMARY KEY auto_increment,
  `key` varchar(80) not null,
  `name` varchar(160) not null,
  `homepage_url` text default (''),
  `terms_url` text default (''),
  `robots_url` text default (''),
  `acquisition` varchar(255) not null default 'licensed_feed',
  `access_policy` varchar(255) not null default 'review_required',
  `status` varchar(255) not null default 'planned',
  `parser_key` varchar(80) default '',
  `priority` integer default 3,
  `poll_minutes` integer default 60,
  `attribution_required` tinyint(1) default 1,
  `retention_days` integer default 365,
  `coverage` text default (''),
  `notes` text default (''),
  `last_policy_review_at` varchar(40) default '',
  `last_successful_ingest_at` varchar(40) default '',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `expert_sources_key` ON `expert_sources` (`key`);
CREATE INDEX `expert_sources_status_policy` ON `expert_sources` (`status`, `access_policy`);
