-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `expert_picks` (
  `id` bigint PRIMARY KEY auto_increment,
  `fingerprint` varchar(255) not null,
  `external_id` varchar(240) default '',
  `market_event_id` bigint,
  `selection_id` bigint,
  `sport` varchar(60) default '',
  `league` varchar(80) default '',
  `event_title` varchar(300) default '',
  `market_type` varchar(80) not null,
  `period` varchar(60) default 'full_game',
  `side` varchar(240) not null,
  `line` decimal(10,2) default 0,
  `has_line` tinyint(1) default 0,
  `odds_american` integer default 0,
  `odds_decimal` decimal(10,2) default 0,
  `sportsbook` varchar(100) default '',
  `units` decimal(10,2) default 0,
  `confidence` decimal(10,2) default 0,
  `rationale` text default (''),
  `starts_at` varchar(40) default '',
  `published_at` varchar(40) not null,
  `last_seen_at` varchar(40) default '',
  `status` varchar(255) not null default 'pending',
  `resulted_at` varchar(40) default '',
  `closing_odds_decimal` decimal(10,2) default 0,
  `clv_pct` decimal(10,2) default 0,
  `profit_units` decimal(10,2) default 0,
  `matched_by` varchar(255) default 'unmatched',
  `match_confidence` decimal(10,2) default 0,
  `expert_source_id` bigint,
  `expert_profile_id` bigint,
  `expert_opinion_id` bigint,
  `market_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `expert_picks_market_event_id_fk` FOREIGN KEY (`market_event_id`) REFERENCES `market_events`(`id`) ON DELETE SET NULL,
  CONSTRAINT `expert_picks_selection_id_fk` FOREIGN KEY (`selection_id`) REFERENCES `selections`(`id`) ON DELETE SET NULL,
  CONSTRAINT `expert_picks_expert_source_id_fk` FOREIGN KEY (`expert_source_id`) REFERENCES `expert_sources`(`id`),
  CONSTRAINT `expert_picks_expert_profile_id_fk` FOREIGN KEY (`expert_profile_id`) REFERENCES `expert_profiles`(`id`),
  CONSTRAINT `expert_picks_expert_opinion_id_fk` FOREIGN KEY (`expert_opinion_id`) REFERENCES `expert_opinions`(`id`),
  CONSTRAINT `expert_picks_market_id_fk` FOREIGN KEY (`market_id`) REFERENCES `markets`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `expert_picks_source_fingerprint` ON `expert_picks` (`expert_source_id`, `fingerprint`);
CREATE INDEX `expert_picks_expert_published` ON `expert_picks` (`expert_profile_id`, `published_at`);
CREATE INDEX `expert_picks_event` ON `expert_picks` (`market_event_id`);
CREATE INDEX `expert_picks_selection` ON `expert_picks` (`selection_id`);
CREATE INDEX `expert_picks_status_starts` ON `expert_picks` (`status`, `starts_at`);
