-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `expert_opinions` (
  `id` bigint PRIMARY KEY auto_increment,
  `external_id` varchar(240) not null,
  `source_document_id` bigint,
  `url` text not null,
  `canonical_url` text default (''),
  `title` varchar(500) not null,
  `content_type` varchar(255) not null default 'article',
  `sport` varchar(60) default '',
  `league` varchar(80) default '',
  `summary` text default (''),
  `excerpt` text default (''),
  `language` varchar(12) default 'en',
  `paywalled` tinyint(1) default 0,
  `published_at` varchar(40) not null,
  `ingested_at` varchar(40) not null,
  `parser_version` varchar(40) default '',
  `content_hash` varchar(64) default '',
  `expert_source_id` bigint,
  `expert_profile_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `expert_opinions_source_document_id_fk` FOREIGN KEY (`source_document_id`) REFERENCES `source_documents`(`id`) ON DELETE SET NULL,
  CONSTRAINT `expert_opinions_expert_source_id_fk` FOREIGN KEY (`expert_source_id`) REFERENCES `expert_sources`(`id`),
  CONSTRAINT `expert_opinions_expert_profile_id_fk` FOREIGN KEY (`expert_profile_id`) REFERENCES `expert_profiles`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `expert_opinions_source_external` ON `expert_opinions` (`expert_source_id`, `external_id`);
CREATE INDEX `expert_opinions_expert_published` ON `expert_opinions` (`expert_profile_id`, `published_at`);
CREATE INDEX `expert_opinions_document` ON `expert_opinions` (`source_document_id`);
CREATE INDEX `expert_opinions_sport_published` ON `expert_opinions` (`sport`, `published_at`);
