-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `referral_codes` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` integer not null,
  `code` varchar(24) not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `referral_codes_user_id_unique` ON `referral_codes` (`user_id`);
CREATE UNIQUE INDEX `referral_codes_code_unique` ON `referral_codes` (`code`);
