-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS `venue_orders` (
  `id` bigint PRIMARY KEY auto_increment,
  `exchange_account_id` bigint,
  `prediction_market_id` bigint,
  `venue` varchar(20),
  `external_order_id` varchar(120),
  `market_external_id` varchar(120),
  `side` varchar(60),
  `limit_price` decimal(10,2),
  `size` decimal(10,2),
  `remaining_size` decimal(10,2),
  `placed_at` varchar(40),
  `synced_at` varchar(40),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `venue_orders_exchange_account_id_fk` FOREIGN KEY (`exchange_account_id`) REFERENCES `exchange_accounts`(`id`),
  CONSTRAINT `venue_orders_prediction_market_id_fk` FOREIGN KEY (`prediction_market_id`) REFERENCES `prediction_markets`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `venue_orders_account_external_id` ON `venue_orders` (`exchange_account_id`, `external_order_id`);
CREATE INDEX `venue_orders_market` ON `venue_orders` (`prediction_market_id`);
